### ISSUE TITLE
Ranks in downloaded SGF are incorrect

### ISSUE THREAD

**Issue by ksafford** [online-go/online-go.com#1137]
**Describe the bug**
When downloading an SGF file of a game played, the players' ranks are incorrect. In my case, it will list both me and my opponent as being 20 or 21  kyu. I noticed this when uploading SGSs to gokibbitz.com where the rank is displayed in the kifu list.
**To Reproduce**
1. Go to game history
2. Download the SGF for some game
3. Inspect the downloaded file.

**Expected behavior**
Expect the rank listed in the SGF corresponds to the rank displayed in the app

**Screenshots**
![image](https://user-images.githubusercontent.com/1257916/81736021-90c53700-945b-11ea-8c4b-edc2c616332e.png)

![image](https://user-images.githubusercontent.com/1257916/81735986-8014c100-945b-11ea-9131-dc5d1a22e432.png)

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Browser Brave

**Comment by JDNdeveloper** [comment]
Just wanted to give this a bump, it's pretty frustrating not having the correct ranks recorded.

**Comment by yayayen11** [comment]
Yeah it could possibly be that OGS ranks are higher? Not sure.

**Comment by EricBackus** [comment]
I have the same issue. For what it's worth, by looking at old downloaded games, I can see that this broke sometime between 2020-04-19 and 2020-04-22. Sure would be nice to have it fixed.

**Comment by ksafford** [comment]
Another piece of data: this only seems to happen for the kyu ranks. Dan ranks are not affected (at least, not always).

**Comment by anoek** [comment]
Fixed yesterday on the backend

**Comment by EricBackus** [comment]
When downloading, now the player ranks in the SGF file are the rank at time of download, not the rank at the time the game was played. Certainly this is better than it was before (where the ranks were completely wrong), but it still doesn't seem right to me.
