### ISSUE TITLE
Misleading `paused_since` after unpausing in `GobanEngineConfig`.

### ISSUE THREAD

**Issue by windo** [online-go/online-go.com#3010]
Server sends `paused_since` in `GobanEngineConfig.clock` if the game was ever paused and does not clear it when the game is unpaused, making it more difficult to tell if the game is paused right now. Basically an API user will have to track the latest seen `GobanEngineConfig.clock.pause` that only appears when the pause state changes, as far as I can tell.

**Comment by lazerwalker** [comment]
I suspect you may have worked around this by now, but on a fresh connection the `game/:id/gamedata` WS message will also contain pause data — if `pause_control` exists in the payload, it will be an `AdHocPauseControl` object. 

IIRC this `pause_control` key is not currently included in the `GobanEngineConfig` type definitions, which is a bug that should be fixed, but if you sniff WS traffic you'll see it's consistently sent.

I agree it would additionally be a server improvement to either make `paused_since` accurate or remove it entirely, since right now it's a frustrating red herring, but you should at least be able to munge out a working pause implementation without it.

**Comment by ogsai** [comment]
Partially addressed: goban PR https://github.com/online-go/goban/pull/217 (merged) moved `pause_control`/`paused_since` into `GobanEngineConfig`'s type definition and added a comment documenting that `paused_since` reflects the last pause start time regardless of current pause state. That fixes the missing-type-definition issue lazerwalker flagged, but the underlying complaint here — that the server keeps `paused_since` stale/set after unpausing instead of clearing it — is still present; that needs a backend change. Leaving open and labeling accordingly.
