### ISSUE TITLE
Visual error on whose player the turn is

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#76]
### Summary

It occured to me very few times, I had just put a stone on the goban and the button "Submit your move" had appeared.
It howed "xxx to move" where x is my opponent's color instead of 'Your move" expected text.

### Environment

 * Operating system:  Android 7.0
 * Browser: Firefox
 * Browser Version: 51.0.3

### Steps To Reproduce:

Can't reproduce it

### Additional Information:

thread in the forums: https://forums.online-go.com/t/visual-error-on-whose-player-the-turn-is/11117

**Comment by anoek** [comment]
Cool, if you happen to notice a pattern or if anyone else happens to experience this, please provide more details until we have a way of reproducing this

**Comment by arnaudgo** [comment]
Hello,

I'm enclosing a screenshot while it's occurring again.

The way to reproduce it is clicking fast on the goban before the misleading text gets updated :)

Programmatically, based on the af009da version of the devel branch, it means that the condition at line 3178 of src/lib/ogs-goban/Goban.ts is checked after the click on the board is processed and that the action processing makes the expression evaluated to false.

![wrong_title_2017_issue76](https://cloud.githubusercontent.com/assets/26174230/23587237/a5fe4ea6-019f-11e7-8601-3e1e5e09122b.png)

**Comment by anoek** [comment]
I'm having a hard time reproducing this, have you seen this issue in awhile @arnaudgo ? I'm wondering if something got fixed along the way since you reported this.

**Comment by arnaudgo** [comment]
Hello @anoek ,

I can always reproduce it on Android and so far I can't on my desktop.
Hereafter, the screenshot of once of my trials today.
You need to click frenetically on some candidate intersection on the board while the page is loading and voilà!
I'm not sure it happens often in real life but at least I can reproduce it :)

Arnaud

![white_to_move-submit](https://cloud.githubusercontent.com/assets/26174230/25187645/8df0a116-251b-11e7-865e-f184843b5399.png)

**Comment by anoek** [comment]
I think this patch should fix it, it's live on the beta server if you want to test it out and let me know :) I still have not been able to reproduce it on my android device :(

**Comment by arnaudgo** [comment]
Hi @anoek, I could not answer before and I would like to know if the patch has been pushed into the production now ? So I don't have to recover my password from OGS Beta website logout from my Android handset, login to the beta, see if I can reproduce it then logout and login back to the production.
It's not a big deal but if I don't bother you, I prefer asking you before :)

Thank you

**Comment by anoek** [comment]
Yep it's in production now :)

**Comment by arnaudgo** [comment]
Hi @anoek :) 

I'm afraid the bug still exists, I could reproduce it easily on production :-/ 

Let me be more precise and clear - if possible - on how to reproduce it:

1°) you visit a game in progress where it's your turn and wait till it's fully loaded
2°) You force the reload of the page
3°) While it's loading, you keep on clicking on a board intersection until you hear the sound of your stone (pump up the volume :) 
4°) When it happens, wait until the page is fully loaded

Then you should see the buttom "Submit move" without "Your move" message but the other one saying it's your opponent's turn.

I stll can reproduce it on my desktop, only on my Android handset, still with Firefox for both.

Not critical, when you reload the page , it solves the problem.

Arnaud
